### ISSUE TITLE
배달캐시큐 앱 삭제

### ISSUE THREAD

**Issue by moonsungjun** [junghum21/android-bdmt_new#1]
![image](https://user-images.githubusercontent.com/19964344/35205869-ddd330a0-ff7b-11e7-9bb8-8354a3446f54.png)

접근권한 허용 및 최신버전으로 업데이트

**Comment by junghum21** [comment]
appcompat v7 적용하기 -> sherlock 삭제
로 진행

**Comment by junghum21** [comment]
완료
