### ISSUE TITLE
배달팡팡 포인트 PUSH알림 문구 수정

### ISSUE THREAD

**Issue by moonsungjun** [junghum21/android-bdmt_new#6]
![screenshot_20180124-140114](https://user-images.githubusercontent.com/19964344/35315614-9dfcae66-0110-11e8-9098-0812bf8cbfc5.png)

---문구 수정---
목포 모임현금북
포인트적립은 하루에 한건만 적립됩니다.
----------------------

**Comment by junghum21** [comment]
웹쪽에서 처리해야 하는 것으로 확인 됨
