### ISSUE TITLE
배달팡팡 "포인트적립 " 2,000점 ?? <--- 이부분 확인 부탁해요

### ISSUE THREAD

**Issue by moonsungjun** [junghum21/android-bdmt_new#7]
http://cashq.co.kr/adm/branch_view.php

![screenshot_20180124-140149](https://user-images.githubusercontent.com/19964344/35316062-e0740454-0112-11e8-9cde-c874ae2737c1.png)

![image](https://user-images.githubusercontent.com/19964344/35316084-ff03c58a-0112-11e8-9364-1f5f48203257.png)

**Comment by junghum21** [comment]
(구) 캐시큐에 있던 소스로 대체
완료
